export type AppConfig = {
  ZOOM_CLIENT_SECRET: string;
  ZOOM_CLIENT_ID: string;
  ZOOM_APP_VERIFICATION: string;
  APP_ENDPOINT: string;
  APP_DOMAIN: string;
  CLOUD_FUNCTION_ENDPOINT__ZOOM_GET_TOKEN_DATA: string;
  CLOUD_FUNCTION_ENDPOINT: string;
  FIRESTORE_PRIVATE_KEY: string;
  FIRESTORE_API_KEY: string;
  FIRESTORE_AUTH_DOMAIN: string;
  FIRESTORE_PROJECT_ID: string;
  GOOGLE_AUTH_CLIENT_ID: string;
  GOOGLE_AUTH_CLIENT_SECRET: string;
  GOOGLE_CALENDAR_API_KEY: string;
  REDIS_IP: string;
  REDIS_PORT: string;
  JWT_SECRET: string;
};
